#!/bin/bash
# Quick Testing Commands for Temporal Semantic Weaving System

echo "🌀 Temporal Semantic Weaving - Quick Test Commands"
echo "=================================================="
echo ""
echo "1️⃣  SETUP (run once):"
echo "   cd /Users/amittiwari/Desktop/tsw-enhanced"
echo "   source .venv/bin/activate"
echo ""
echo "2️⃣  TEST SINGLE DOMAINS:"
echo "   python test_scenarios.py tech        # Technology learning"
echo "   python test_scenarios.py personal    # Personal life patterns"
echo "   python test_scenarios.py travel      # Travel & adventure"
echo "   python test_scenarios.py health      # Health & fitness"
echo "   python test_scenarios.py academic    # Academic research"
echo "   python test_scenarios.py cooking     # Cooking & recipes"
echo ""
echo "3️⃣  TEST ALL DOMAINS AT ONCE:"
echo "   python test_scenarios.py all"
echo ""
echo "4️⃣  INTERACTIVE MODE (add your own experiences):"
echo "   python interactive_test.py"
echo ""
echo "5️⃣  SEE EXAMPLES ACROSS DOMAINS:"
echo "   python TESTING_GUIDE.py"
echo ""
echo "6️⃣  ORIGINAL DEMO:"
echo "   python demo.py"
echo ""
echo "7️⃣  VIEW DOCUMENTATION:"
echo "   cat TESTING_README.md               # Testing guide"
echo "   cat CODEBASE_ANALYSIS.md            # System architecture"
echo "   cat COMPLETE_TESTING_SUMMARY.md     # Full summary"
echo ""
echo "=================================================="
echo "✨ System is ready! Pick a command above to start."
echo "=================================================="
